package WikiPoliticos::Web::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'WikiPoliticos::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=wikipoliticos;host=127.0.0.1',
        user => 'wikipoliticos',
        password => 'wikipoliticos',
        loader_options => {components => ["InflateColumn::DateTime","TimeStamp"],generate_pod => 0,moniker_map => {candidates_donations_2012 => "CandidateDonation2012"}},
        enable_pg_utf8 => 1,
    }
);

=head1 NAME

WikiPoliticos::Web::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<WikiPoliticos::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<WikiPoliticos::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

sgrs

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
